# Generated by Django 5.0.6 on 2024-07-07 23:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_initial'),
        ('user', '0002_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginformation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='billinginformation',
            name='customer',
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='receiver_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='receiver_name',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='receiver_number',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.MaxLengthValidator(11), django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25),
        ),
        migrations.AddField(
            model_name='item',
            name='shopping_cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.shoppingcart'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('billing_format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.billinginformation')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.shoppingcart')),
            ],
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
